export const killers = [
  { name: `The Trapper`, addons: `theTrapper` },
  { name: `The Hag`, addons: `theHag` },
  { name: `The Cannibal`, addons: `theCannibal` },
  { name: `The Doctor`, addons: `theDoctor` },
  { name: `The Hillbilly`, addons: `theHillbilly` },
  { name: `The Nightmare`, addons: `theNightmare` },
  { name: `The Shape`, addons: `theShape` },
  { name: `The Legion`, addons: `theLegion` },
  { name: `The Huntress`, addons: `theHuntress` },
  { name: `The Pig`, addons: `thePig` },
  { name: `The GhostFace`, addons: `theGhostFace` },
  { name: `The Demogorgon`, addons: `theDemogorgon` },
  { name: `The Nurse`, addons: `theNurse` },
  { name: `The Clown`, addons: `theClown` },
  { name: `The Deathslinger`, addons: `theDeathslinger` },
  { name: `The Plague`, addons: `thePlague` },
  { name: `The Wraith`, addons: `theWraith` },
  { name: `The Spirit`, addons: `theSpirit` },
  { name: `The Oni`, addons: `theOni` },
]