import { IRank } from "../Common/rank.model"

export const theTrapper = [
  { icon: `trapperSack.png`, name: `Trapper Sack`, rank: IRank.BROWN },
  { icon: `trapperGloves.png`, name: `Trapper Gloves`, rank: IRank.BROWN },
  { icon: `strongCoilSpring.png`, name: `Strong Coil Spring`, rank: IRank.BROWN },
  { icon: `paddedJaws.png`, name: `Padded Jaws`, rank: IRank.BROWN },
  { icon: `trapperBag.png`, name: `Trapper Bag`, rank: IRank.YELLOW },
  { icon: `trapSetters.png`, name: `Trap Setters`, rank: IRank.YELLOW },
  { icon: `serratedJaws.png`, name: `Serrated Jaws`, rank: IRank.YELLOW },
  { icon: `logwoodDye.png`, name: `Logwood Dye`, rank: IRank.YELLOW },
  { icon: `4-coilSpringKit.png`, name: `4-Coil Spring Kit`, rank: IRank.YELLOW },
  { icon: `waxBrick.png`, name: `Wax Brick`, rank: IRank.GREEN },
  { icon: `tarBottle.png`, name: `Tar Bottle`, rank: IRank.GREEN },
  { icon: `settingTools.png`, name: `Setting Tools`, rank: IRank.GREEN },
  { icon: `secondaryCoil.png`, name: `Secondary Coil`, rank: IRank.GREEN },
  { icon: `rustedJaws.png`, name: `Rusted Jaws`, rank: IRank.GREEN },
  { icon: `stitchedBag.png`, name: `Stitched Bag`, rank: IRank.PURPLE },
  { icon: `oilyCoil.png`, name: `Oily Coil`, rank: IRank.PURPLE },
  { icon: `honingStone.png`, name: `Honing Stone`, rank: IRank.PURPLE },
  { icon: `fasteningTools.png`, name: `Fastening Tools`, rank: IRank.PURPLE },
  { icon: `iridescentStone.png`, name: `Iridescent Stone`, rank: IRank.IRIDESCANT },
  { icon: `bloodyCoil.png`, name: `Bloody Coil`, rank: IRank.IRIDESCANT },
]

export const theHag = [
  { icon: `ropeNecklet.png`, name: `Rope Necklet`, rank: IRank.BROWN },
  { icon: `powderedEggshell.png`, name: `Powdered Eggshell`, rank: IRank.BROWN },
  { icon: `deadFlyMud.png`, name: `Dead Fly Mud`, rank: IRank.BROWN },
  { icon: `bogWater.png`, name: `Bog Water`, rank: IRank.BROWN },
  { icon: `pussyWillowCatkins.png`, name: `Pussy Willow Catkins`, rank: IRank.YELLOW },
  { icon: `halfEggshell.png`, name: `Half Eggshell`, rank: IRank.YELLOW },
  { icon: `dragonflyWings.png`, name: `Dragonfly Wings`, rank: IRank.YELLOW },
  { icon: `cypressNecklet.png`, name: `Cypress Necklet`, rank: IRank.YELLOW },
  { icon: `bloodiedWater.png`, name: `Bloodied Water`, rank: IRank.YELLOW },
  { icon: `willowWreath.png`, name: `Willow Wreath`, rank: IRank.GREEN },
  { icon: `swampOrchidNecklet.png`, name: `Swamp Orchid Necklet`, rank: IRank.GREEN },
  { icon: `driedCicada.png`, name: `Dried Cicada`, rank: IRank.GREEN },
  { icon: `crackedTurtleEgg.png`, name: `Cracked Turtle Egg`, rank: IRank.GREEN },
  { icon: `bloodiedMud.png`, name: `Bloodied Mud`, rank: IRank.GREEN },
  { icon: `scarredHand.png`, name: `Scarred Hand`, rank: IRank.PURPLE },
  { icon: `rustyShackles.png`, name: `Rusty Shackles`, rank: IRank.PURPLE },
  { icon: `granmasHeart.png`, name: `Grandma's Heart`, rank: IRank.PURPLE },
  { icon: `disfiguredEar.png`, name: `Disfigured Ear`, rank: IRank.PURPLE },
  { icon: `waterloggedShoe.png`, name: `Waterlogged Shoe`, rank: IRank.IRIDESCANT },
  { icon: `mintRag.png`, name: `Mint Rag`, rank: IRank.IRIDESCANT },
]

export const theCannibal = [
  { icon: `vegetableOil.png`, name: `Vegetable Oil`, rank: IRank.BROWN },
  { icon: `sparkPlug.png`, name: `Spark Plug`, rank: IRank.BROWN },
  { icon: `chainsawFile.png`, name: `Chainsaw File`, rank: IRank.BROWN },
  { icon: `speedLimiter.png`, name: `Speed Limiter`, rank: IRank.YELLOW },
  { icon: `shopLubricant.png`, name: `Shop Lubricant`, rank: IRank.YELLOW },
  { icon: `primerBulb.png`, name: `Primer Bulb`, rank: IRank.YELLOW },
  { icon: `longGuideBar.png`, name: `Long Guide Bar`, rank: IRank.YELLOW },
  { icon: `knifeScratches.png`, name: `Knife Scratches`, rank: IRank.YELLOW },
  { icon: `homemadeMuffler.png`, name: `Homemade Muffler`, rank: IRank.YELLOW },
  { icon: `grislyChains.png`, name: `Grisly Chains`, rank: IRank.YELLOW },
  { icon: `depthGaugeRake.png`, name: `Depth Gauge Rake`, rank: IRank.YELLOW },
  { icon: `chilli.png`, name: `Chilli`, rank: IRank.YELLOW },
  { icon: `theGrease.png`, name: `The Grease`, rank: IRank.GREEN },
  { icon: `theBeastsMarks.png`, name: `The Beast's Marks`, rank: IRank.GREEN },
  { icon: `rustedChains.png`, name: `Rusted Chains`, rank: IRank.GREEN },
  { icon: `lightChassis.png`, name: `Light Chassis`, rank: IRank.GREEN },
  { icon: `carburettorTuningGuide.png`, name: `Carburettor Tuning Guide`, rank: IRank.GREEN },
  { icon: `begrimedChains.png`, name: `Begrimed Chains`, rank: IRank.PURPLE },
  { icon: `award-winningChilli.png`, name: `Award-winning Chilli`, rank: IRank.PURPLE },
]

export const theDoctor = [
  { icon: `moldyElectrode.png`, name: `Mouldy Electrode`, rank: IRank.BROWN },
  { icon: `mapleKnight.png`, name: `Maple Knight`, rank: IRank.BROWN },
  { icon: `orderClassI.png`, name: `"Order" - Class I`, rank: IRank.BROWN },
  { icon: `calmClassI.png`, name: `"Calm" - Class I`, rank: IRank.BROWN },
  { icon: `polishedElectrode.png`, name: `Polished Electrode`, rank: IRank.YELLOW },
  { icon: `restraintClassII.png`, name: `"Restraint" - Class II`, rank: IRank.YELLOW },
  { icon: `orderClassII.png`, name: `"Order" - Class II`, rank: IRank.YELLOW },
  { icon: `disciplineClassII.png`, name: `"Discipline" - Class II`, rank: IRank.YELLOW },
  { icon: `calmClassII.png`, name: `"Calm" - Class II`, rank: IRank.YELLOW },
  { icon: `scrappedTape.png`, name: `Scrapped Tape`, rank: IRank.GREEN },
  { icon: `interviewTape.png`, name: `Interview Tape`, rank: IRank.GREEN },
  { icon: `highStimulusElectrode.png`, name: `High Stimulus Electrode`, rank: IRank.GREEN },
  { icon: `restraintClassIII.png`, name: `"Restraint" - Class III`, rank: IRank.GREEN },
  { icon: `disciplineClassIII.png`, name: `"Discipline" - Class III`, rank: IRank.GREEN },
  { icon: `restraintCartersNotes.png`, name: `"Restraint" - Carter's Notes`, rank: IRank.PURPLE },
  { icon: `orderCartersNotes.png`, name: `"Order" - Carter's Notes`, rank: IRank.PURPLE },
  { icon: `disciplineCartersNotes.png`, name: `"Discipline" - Carter's Notes`, rank: IRank.PURPLE },
  { icon: `calmCartersNotes.png`, name: `"Calm" - Carter's Notes`, rank: IRank.PURPLE },
  { icon: `iridescentQueen.png`, name: `Iridescent Queen`, rank: IRank.IRIDESCANT },
  { icon: `iridescentKing.png`, name: `Iridescent King`, rank: IRank.IRIDESCANT },
]

export const theHillbilly = [
  { icon: `vegetableOil.png`, name: `Vegetable Oil`, rank: IRank.BROWN },
  { icon: `sparkPlug.png`, name: `Spark Plug`, rank: IRank.BROWN },
  { icon: `chainsawFile.png`, name: `Chainsaw File`, rank: IRank.BROWN },
  { icon: `spikedBoots.png`, name: `Spiked Boots`, rank: IRank.YELLOW },
  { icon: `speedLimiter.png`, name: `Speed Limiter`, rank: IRank.YELLOW },
  { icon: `shopLubricant.png`, name: `Shop Lubricant`, rank: IRank.YELLOW },
  { icon: `primerBulb.png`, name: `Primer Bulb`, rank: IRank.YELLOW },
  { icon: `longGuideBar.png`, name: `Long Guide Bar`, rank: IRank.YELLOW },
  { icon: `homemadeMuffler.png`, name: `Homemade Muffler`, rank: IRank.YELLOW },
  { icon: `grislyChains.png`, name: `Grisly Chains`, rank: IRank.YELLOW },
  { icon: `depthGaugeRake.png`, name: `Depth Gauge Rake`, rank: IRank.YELLOW },
  { icon: `deathEngravings.png`, name: `Death Engravings`, rank: IRank.YELLOW },
  { icon: `theThompsonsMix.png`, name: `The Thompson's Mix`, rank: IRank.GREEN },
  { icon: `rustedChains.png`, name: `Rusted Chains`, rank: IRank.GREEN },
  { icon: `lightChassis.png`, name: `Light Chassis`, rank: IRank.GREEN },
  { icon: `doomEngravings.png`, name: `Doom Engravings`, rank: IRank.GREEN },
  { icon: `carburettorTuningGuide.png`, name: `Carburettor Tuning Guide`, rank: IRank.GREEN },
  { icon: `thompsonsMoonshine.png`, name: `Thompson's Moonshine`, rank: IRank.PURPLE },
  { icon: `begrimedChains.png`, name: `Begrimed Chains`, rank: IRank.PURPLE },
]

export const theNightmare = [
  { icon: `woolShirt.png`, name: `Wool Shirt`, rank: IRank.BROWN },
  { icon: `sheepBlock.png`, name: `Sheep Block`, rank: IRank.BROWN },
  { icon: `kidsDrawing.png`, name: `Kid's Drawing`, rank: IRank.BROWN },
  { icon: `gardenRake.png`, name: `Garden Rake`, rank: IRank.BROWN },
  { icon: `prototypeClaws.png`, name: `Prototype Claws`, rank: IRank.YELLOW },
  { icon: `outdoorRope.png`, name: `Outdoor Rope`, rank: IRank.YELLOW },
  { icon: `nancysSketch.png`, name: `Nancy's Sketch`, rank: IRank.YELLOW },
  { icon: `greenDress.png`, name: `Green Dress`, rank: IRank.YELLOW },
  { icon: `catBlock.png`, name: `Cat Block`, rank: IRank.YELLOW },
  { icon: `unicornBlock.png`, name: `Unicorn Block`, rank: IRank.GREEN },
  { icon: `paintThinner.png`, name: `Paint Thinner`, rank: IRank.GREEN },
  { icon: `nancysMasterpiece.png`, name: `Nancy's Masterpiece`, rank: IRank.GREEN },
  { icon: `jumpRope.png`, name: `Jump Rope`, rank: IRank.GREEN },
  { icon: `blueDress.png`, name: `Blue Dress`, rank: IRank.GREEN },
  { icon: `pillBottle.png`, name: `Pill Bottle`, rank: IRank.PURPLE },
  { icon: `swingChains.png`, name: `Swing Chains`, rank: IRank.PURPLE },
  { icon: `classPhoto.png`, name: `Class Photo`, rank: IRank.PURPLE },
  { icon: `zBlock.png`, name: `"Z" Block`, rank: IRank.PURPLE },
  { icon: `redPaintBrush.png`, name: `Red Paint Brush`, rank: IRank.IRIDESCANT },
  { icon: `blackBox.png`, name: `Black Box`, rank: IRank.IRIDESCANT },
]

export const theShape = [
  { icon: `tackyEarrings.png`, name: `Tacky Earrings`, rank: IRank.BROWN },
  { icon: `boyfriendsMemo.png`, name: `Boyfriend's Memo`, rank: IRank.BROWN },
  { icon: `blondeHair.png`, name: `Blond Hair`, rank: IRank.BROWN },
  { icon: `reflectiveFragment.png`, name: `Reflective Fragment`, rank: IRank.YELLOW },
  { icon: `memorialFlower.png`, name: `Memorial Flower`, rank: IRank.YELLOW },
  { icon: `jewellery.png`, name: `Jewellery`, rank: IRank.YELLOW },
  { icon: `hairBrush.png`, name: `Hair Brush`, rank: IRank.YELLOW },
  { icon: `glassFragment.png`, name: `Glass Fragment`, rank: IRank.YELLOW },
  { icon: `deadRabbit.png`, name: `Dead Rabbit`, rank: IRank.YELLOW },
  { icon: `mirrorShard.png`, name: `Mirror Shard`, rank: IRank.GREEN },
  { icon: `judithsJournal.png`, name: `Judith's Journal`, rank: IRank.GREEN },
  { icon: `jewelleryBox.png`, name: `Jewellery Box`, rank: IRank.GREEN },
  { icon: `jMyersMemorial.png`, name: `J. Myers Memorial`, rank: IRank.GREEN },
  { icon: `hairBow.png`, name: `Hair Bow`, rank: IRank.GREEN },
  { icon: `vanityMirror.png`, name: `Vanity Mirror`, rank: IRank.PURPLE },
  { icon: `tombstonePiece.png`, name: `Tombstone Piece`, rank: IRank.PURPLE },
  { icon: `scratchedMirror.png`, name: `Scratched Mirror`, rank: IRank.PURPLE },
  { icon: `lockOfHair.png`, name: `Lock of Hair`, rank: IRank.PURPLE },
  { icon: `judithsTombstone.png`, name: `Judith's Tombstone`, rank: IRank.IRIDESCANT },
  { icon: `fragrantTuftOfHair.png`, name: `Fragrant Tuft of Hair`, rank: IRank.IRIDESCANT },
]

export const theLegion = [
  { icon: `smileyFacePin.png`, name: `Smiley Face Pin`, rank: IRank.BROWN },
  { icon: `scratchedRuler.png`, name: `Scratched Ruler`, rank: IRank.BROWN },
  { icon: `mischiefList.png`, name: `Mischief List`, rank: IRank.BROWN },
  { icon: `friendshipBracelet.png`, name: `Friendship Bracelet`, rank: IRank.BROWN },
  { icon: `never-SleepPills.png`, name: `Never-Sleep Pills`, rank: IRank.YELLOW },
  { icon: `muralSketch.png`, name: `Mural Sketch`, rank: IRank.YELLOW },
  { icon: `juliesMixTape.png`, name: `Julie's Mix Tape`, rank: IRank.YELLOW },
  { icon: `etchedRuler.png`, name: `Etched Ruler`, rank: IRank.YELLOW },
  { icon: `defacedSmileyPin.png`, name: `Defaced Smiley Pin`, rank: IRank.YELLOW },
  { icon: `theLegionPin.png`, name: `The Legion Pin`, rank: IRank.GREEN },
  { icon: `susiesMixTape.png`, name: `Susie's Mix Tape`, rank: IRank.GREEN },
  { icon: `stolenSketchBook.png`, name: `Stolen Sketch Book`, rank: IRank.GREEN },
  { icon: `nastyBlade.png`, name: `Nasty Blade`, rank: IRank.GREEN },
  { icon: `joeysMixTape.png`, name: `Joey's Mix Tape`, rank: IRank.GREEN },
  { icon: `stabWoundsStudy.png`, name: `Stab Wounds Study`, rank: IRank.PURPLE },
  { icon: `franksMixTape.png`, name: `Frank's Mix Tape`, rank: IRank.PURPLE },
  { icon: `filthyBlade.png`, name: `Filthy Blade`, rank: IRank.PURPLE },
  { icon: `coldDirt.png`, name: `Cold Dirt`, rank: IRank.PURPLE },
  { icon: `iridescentButton.png`, name: `Iridescent Button`, rank: IRank.IRIDESCANT },
  { icon: `fumingMixTape.png`, name: `Fuming Mix Tape`, rank: IRank.IRIDESCANT },
]

export const theHuntress = [
  { icon: `coarseStone.png`, name: `Coarse Stone`, rank: IRank.BROWN },
  { icon: `berusToxin.png`, name: `Berus Toxin`, rank: IRank.BROWN },
  { icon: `bandagedHaft.png`, name: `Bandaged Haft`, rank: IRank.BROWN },
  { icon: `amanitaToxin.png`, name: `Amanita Toxin`, rank: IRank.BROWN },
  { icon: `yewSeedBrew.png`, name: `Yew Seed Brew`, rank: IRank.YELLOW },
  { icon: `shinyPin.png`, name: `Shiny Pin`, rank: IRank.YELLOW },
  { icon: `oakHaft.png`, name: `Oak Haft`, rank: IRank.YELLOW },
  { icon: `mannaGrassBraid.png`, name: `Manna Grass Braid`, rank: IRank.YELLOW },
  { icon: `leatherLoop.png`, name: `Leather Loop`, rank: IRank.YELLOW },
  { icon: `fineStone.png`, name: `Fine Stone`, rank: IRank.YELLOW },
  { icon: `deerskinGloves.png`, name: `Deerskin Gloves`, rank: IRank.YELLOW },
  { icon: `yewSeedConcoction.png`, name: `Yew Seed Concoction`, rank: IRank.GREEN },
  { icon: `venomousConcoction.png`, name: `Venomous Concoction`, rank: IRank.GREEN },
  { icon: `rustyHead.png`, name: `Rusty Head`, rank: IRank.GREEN },
  { icon: `pungentPhial.png`, name: `Pungent Phial`, rank: IRank.GREEN },
  { icon: `flowerBabushka.png`, name: `Flower Babushka`, rank: IRank.GREEN },
  { icon: `infantryBelt.png`, name: `Infantry Belt`, rank: IRank.PURPLE },
  { icon: `glowingConcoction.png`, name: `Glowing Concoction`, rank: IRank.PURPLE },
  { icon: `begrimedHead.png`, name: `Begrimed Head`, rank: IRank.PURPLE },
  { icon: `iridescentHead.png`, name: `Iridescent Head`, rank: IRank.IRIDESCANT },
]

export const thePig = [
  { icon: `workshopGrease.png`, name: `Workshop Grease`, rank: IRank.BROWN },
  { icon: `shatteredSyringe.png`, name: `Shattered Syringe`, rank: IRank.BROWN },
  { icon: `johnsMedicalFile.png`, name: `John's Medical File`, rank: IRank.BROWN },
  { icon: `combatStraps.png`, name: `Combat Straps`, rank: IRank.BROWN },
  { icon: `videoTape.png`, name: `Video Tape`, rank: IRank.YELLOW },
  { icon: `utilityBlades.png`, name: `Utility Blades`, rank: IRank.YELLOW },
  { icon: `razorWires.png`, name: `Razor Wires`, rank: IRank.YELLOW },
  { icon: `lastWill.png`, name: `Last Will`, rank: IRank.YELLOW },
  { icon: `faceMask.png`, name: `Face Mask`, rank: IRank.YELLOW },
  { icon: `slow-ReleaseToxin.png`, name: `Slow-Release Toxin`, rank: IRank.GREEN },
  { icon: `rustyAttachments.png`, name: `Rusty Attachments`, rank: IRank.GREEN },
  { icon: `jigsawsAnnotatedPlan.png`, name: `Jigsaw's Annotated Plan`, rank: IRank.GREEN },
  { icon: `interlockingRazor.png`, name: `Interlocking Razor`, rank: IRank.GREEN },
  { icon: `bagOfGears.png`, name: `Bag of Gears`, rank: IRank.GREEN },
  { icon: `tamperedTimer.png`, name: `Tampered Timer`, rank: IRank.PURPLE },
  { icon: `jigsawsSketch.png`, name: `Jigsaw's Sketch`, rank: IRank.PURPLE },
  { icon: `crateOfGears.png`, name: `Crate of Gears`, rank: IRank.PURPLE },
  { icon: `amandasSecret.png`, name: `Amanda's Secret`, rank: IRank.PURPLE },
  { icon: `rulesSetNo.2.png`, name: `Rules Set No.2`, rank: IRank.IRIDESCANT },
  { icon: `amandasLetter.png`, name: `Amanda's Letter`, rank: IRank.IRIDESCANT },
]

export const theGhostFace = [
  { icon: `philly.png`, name: `"Philly"`, rank: IRank.BROWN },
  { icon: `walleyesMatchbook.png`, name: `Walleyes Matchbook`, rank: IRank.BROWN },
  { icon: `headlinesCutouts.png`, name: `Headlines Cut-outs`, rank: IRank.BROWN },
  { icon: `cheapCologne.png`, name: `Cheap Cologne`, rank: IRank.BROWN },
  { icon: `telephotoLens.png`, name: `Telephoto Lens`, rank: IRank.YELLOW },
  { icon: `reusuableCinchStraps.png`, name: `Reusable Cinch Straps`, rank: IRank.YELLOW },
  { icon: `olsensJournal.png`, name: `Olsen's Journal`, rank: IRank.YELLOW },
  { icon: `olsensAddressBook.png`, name: `Olsen's Address Book`, rank: IRank.YELLOW },
  { icon: `markedMap.png`, name: `Marked Map`, rank: IRank.YELLOW },
  { icon: `olsensWallet.png`, name: `Olsen's Wallet`, rank: IRank.GREEN },
  { icon: `leatherKnifeSheath.png`, name: `Leather Knife Sheath`, rank: IRank.GREEN },
  { icon: `lastingPerfume.png`, name: `Lasting Perfume`, rank: IRank.GREEN },
  { icon: `knifeBeltClip.png`, name: `Knife Belt Clip`, rank: IRank.GREEN },
  { icon: `chewedPen.png`, name: `Chewed Pen`, rank: IRank.GREEN },
  { icon: `victimsDetailedRoutine.png`, name: `Victim's Detailed Routine`, rank: IRank.PURPLE },
  { icon: `nightvisionMonocular.png`, name: `Night Vision Monocular`, rank: IRank.PURPLE },
  { icon: `drop-LegKnifeSheath.png`, name: `Drop-Leg Knife Sheath`, rank: IRank.PURPLE },
  { icon: `driversLicense.png`, name: `Driver's License`, rank: IRank.PURPLE },
  { icon: `caughtOnTape.png`, name: `"Ghost Face Caught on Tape"`, rank: IRank.IRIDESCANT },
  { icon: `outdoorSecurityCamera.png`, name: `Outdoor Security Camera`, rank: IRank.IRIDESCANT },
]

export const theDemogorgon = [
  { icon: `rottenPumpkin.png`, name: `Rotten Pumpkin`, rank: IRank.BROWN },
  { icon: `blackHeart.png`, name: `Black Heart`, rank: IRank.BROWN },
  { icon: `ratLiver.png`, name: `Rat Liver`, rank: IRank.BROWN },
  { icon: `ratTail.png`, name: `Rat Tail`, rank: IRank.BROWN },
  { icon: `stickyLining.png`, name: `Sticky Lining`, rank: IRank.YELLOW },
  { icon: `viscousWebbing.png`, name: `Viscous Webbing`, rank: IRank.YELLOW },
  { icon: `rottenGreenTripe.png`, name: `Rotten Green Tripe`, rank: IRank.YELLOW },
  { icon: `mewsGuts.png`, name: `Mew's Guts`, rank: IRank.YELLOW },
  { icon: `barbsGlasses.png`, name: `Barb's Glasses`, rank: IRank.YELLOW },
  { icon: `elevensSoda.png`, name: `Eleven's Soda`, rank: IRank.GREEN },
  { icon: `thornyVines.png`, name: `Thorny Vines`, rank: IRank.GREEN },
  { icon: `brassCaseLighter.png`, name: `Brass Case Lighter`, rank: IRank.GREEN },
  { icon: `violetWaxcap.png`, name: `Violet Waxcap`, rank: IRank.GREEN },
  { icon: `deerLung.png`, name: `Deer Lung`, rank: IRank.GREEN },
  { icon: `lifeguardWhistle.png`, name: `Lifeguard Whistle`, rank: IRank.PURPLE },
  { icon: `vermilionWebcap.png`, name: `Vermilion Webcap`, rank: IRank.PURPLE },
  { icon: `upsideDownResin.png`, name: `Upside Down Resin`, rank: IRank.PURPLE },
  { icon: `unknownEgg.png`, name: `Unknown Egg`, rank: IRank.PURPLE },
  { icon: `leproseLichen.png`, name: `Leprose Lichen`, rank: IRank.IRIDESCANT },
  { icon: `redMoss.png`, name: `Red Moss`, rank: IRank.IRIDESCANT },
]

export const theNurse = [
  { icon: `woodenHorse.png`, name: `Wooden Horse`, rank: IRank.BROWN },
  { icon: `whiteNitComb.png`, name: `White Nit Comb`, rank: IRank.BROWN },
  { icon: `plaidFlannel.png`, name: `Plaid Flannel`, rank: IRank.BROWN },
  { icon: `metalSpoon.png`, name: `Metal Spoon`, rank: IRank.BROWN },
  { icon: `pocketWatch.png`, name: `Pocket Watch`, rank: IRank.YELLOW },
  { icon: `dullBracelet.png`, name: `Dull Bracelet`, rank: IRank.YELLOW },
  { icon: `darkCincture.png`, name: `Dark Cincture`, rank: IRank.YELLOW },
  { icon: `catatonicBoysTreasure.png`, name: `Catatonic Boy's Treasure`, rank: IRank.YELLOW },
  { icon: `badManKeepsake.png`, name: `Bad Man Keepsake`, rank: IRank.YELLOW },
  { icon: `spasmodicBreath.png`, name: `Spasmodic Breath`, rank: IRank.GREEN },
  { icon: `heavyPanting.png`, name: `Heavy Panting`, rank: IRank.GREEN },
  { icon: `fragileWheeze.png`, name: `Fragile Wheeze`, rank: IRank.GREEN },
  { icon: `ataxicRespiration.png`, name: `Ataxic Respiration`, rank: IRank.GREEN },
  { icon: `anxiousGasp.png`, name: `Anxious Gasp`, rank: IRank.GREEN },
  { icon: `kavanaghsLastBreath.png`, name: `Kavanagh's Last Breath`, rank: IRank.PURPLE },
  { icon: `jennersLastBreath.png`, name: `Jenner's Last Breath`, rank: IRank.PURPLE },
  { icon: `campbellsLastBreath.png`, name: `Campbell's Last Breath`, rank: IRank.PURPLE },
  { icon: `badMansLastBreath.png`, name: `"Bad Man's" Last Breath`, rank: IRank.PURPLE },
  { icon: `tornBookmark.png`, name: `Torn Bookmark`, rank: IRank.IRIDESCANT },
  { icon: `matchbox.png`, name: `Matchbox`, rank: IRank.IRIDESCANT },
]

export const theClown = [
  { icon: `smellyInnerSoles.png`, name: `Smelly Inner Soles`, rank: IRank.BROWN },
  { icon: `robinFeather.png`, name: `Robin Feather`, rank: IRank.BROWN },
  { icon: `fingerlessParadeGloves.png`, name: `Fingerless Parade Gloves`, rank: IRank.BROWN },
  { icon: `ether5Vol.png`, name: `Ether 5 Vol%`, rank: IRank.BROWN },
  { icon: `thickCorkStopper.png`, name: `Thick Cork Stopper`, rank: IRank.YELLOW },
  { icon: `stickySodaBottle.png`, name: `Sticky Soda Bottle`, rank: IRank.YELLOW },
  { icon: `starlingFeather.png`, name: `Starling Feather`, rank: IRank.YELLOW },
  { icon: `solventJug.png`, name: `Solvent Jug`, rank: IRank.YELLOW },
  { icon: `keroseneCan.png`, name: `Kerosene Can`, rank: IRank.YELLOW },
  { icon: `vhsPorn.png`, name: `VHS Porn`, rank: IRank.GREEN },
  { icon: `sulphuricAcidVial.png`, name: `Sulphuric Acid Vial`, rank: IRank.GREEN },
  { icon: `flaskOfBleach.png`, name: `Flask of Bleach`, rank: IRank.GREEN },
  { icon: `ether10Vol.png`, name: `Ether 10 Vol%`, rank: IRank.GREEN },
  { icon: `bottleOfChloroform.png`, name: `Bottle Of Chloroform`, rank: IRank.GREEN },
  { icon: `garishMake-UpKit.png`, name: `Garish Make-up Kit`, rank: IRank.PURPLE },
  { icon: `ether15Vol.png`, name: `Ether 15 Vol%`, rank: IRank.PURPLE },
  { icon: `cigarBox.png`, name: `Cigar Box`, rank: IRank.PURPLE },
  { icon: `cheapGinBottle.png`, name: `Cheap Gin Bottle`, rank: IRank.PURPLE },
  { icon: `tattoosMiddleFinger.png`, name: `Tattoo's Middle Finger`, rank: IRank.IRIDESCANT },
  { icon: `redheadsPinkyFinger.png`, name: `Redhead's Pinky Finger`, rank: IRank.IRIDESCANT },
]

export const theDeathslinger = [
  { icon: `spitPolishRag.png`, name: `Spit Polish Rag`, rank: IRank.BROWN },
  { icon: `snakeOil.png`, name: `Snake Oil`, rank: IRank.BROWN },
  { icon: `ricketyChain.png`, name: `Rickety Chain`, rank: IRank.BROWN },
  { icon: `modifiedAmmoBelt.png`, name: `Modified Ammo Belt`, rank: IRank.BROWN },
  { icon: `rustedSpike.png`, name: `Rusted Spike`, rank: IRank.YELLOW },
  { icon: `poisonOakLeaves.png`, name: `Poison Oak Leaves`, rank: IRank.YELLOW },
  { icon: `marshalsBadge.png`, name: `Marshal's Badge`, rank: IRank.YELLOW },
  { icon: `jawSmasher.png`, name: `Jaw Smasher`, rank: IRank.YELLOW },
  { icon: `chewingTobacco.png`, name: `Chewing Tobacco`, rank: IRank.YELLOW },
  { icon: `wardensKeys.png`, name: `Warden's Keys`, rank: IRank.GREEN },
  { icon: `wantedPoster.png`, name: `Wanted Poster`, rank: IRank.GREEN },
  { icon: `tinOilCan.png`, name: `Tin Oil Can`, rank: IRank.GREEN },
  { icon: `honeyLocustThorn.png`, name: `Honey Locust Thorn`, rank: IRank.GREEN },
  { icon: `bayshoresGoldTooth.png`, name: `Bayshore's Gold Tooth`, rank: IRank.GREEN },
  { icon: `prisonChain.png`, name: `Prison Chain`, rank: IRank.PURPLE },
  { icon: `goldCreekWhiskey.png`, name: `Gold Creek Whiskey`, rank: IRank.PURPLE },
  { icon: `bayshoresCigar.png`, name: `Bayshore's Cigar`, rank: IRank.PURPLE },
  { icon: `barbedWire.png`, name: `Barbed Wire`, rank: IRank.PURPLE },
  { icon: `iridescentCoin.png`, name: `Iridescent Coin`, rank: IRank.IRIDESCANT },
  { icon: `hellshireIron.png`, name: `Hellshire Iron`, rank: IRank.IRIDESCANT },
]

export const thePlague = [
  { icon: `prayerTabletFragment.png`, name: `Prayer Tablet Fragment`, rank: IRank.BROWN },
  { icon: `olibanumIncense.png`, name: `Olibanum Incense`, rank: IRank.BROWN },
  { icon: `limestoneSeal.png`, name: `Limestone Seal`, rank: IRank.BROWN },
  { icon: `healingSalve.png`, name: `Healing Salve`, rank: IRank.BROWN },
  { icon: `prophylacticAmulet.png`, name: `Prophylactic Amulet`, rank: IRank.YELLOW },
  { icon: `potentTincture.png`, name: `Potent Tincture`, rank: IRank.YELLOW },
  { icon: `haematiteSeal.png`, name: `Haematite Seal`, rank: IRank.YELLOW },
  { icon: `emeticPotion.png`, name: `Emetic Potion`, rank: IRank.YELLOW },
  { icon: `blessedApple.png`, name: `Blessed Apple`, rank: IRank.YELLOW },
  { icon: `rubbingOil.png`, name: `Rubbing Oil`, rank: IRank.GREEN },
  { icon: `infectedEmetic.png`, name: `Infected Emetic`, rank: IRank.GREEN },
  { icon: `incensedOintment.png`, name: `Incensed Ointment`, rank: IRank.GREEN },
  { icon: `exorcismAmulet.png`, name: `Exorcism Amulet`, rank: IRank.GREEN },
  { icon: `ashenApple.png`, name: `Ashen Apple`, rank: IRank.GREEN },
  { icon: `worshipTablet.png`, name: `Worship Tablet`, rank: IRank.PURPLE },
  { icon: `vileEmetic.png`, name: `Vile Emetic`, rank: IRank.PURPLE },
  { icon: `severedToe.png`, name: `Severed Toe`, rank: IRank.PURPLE },
  { icon: `devoteesAmulet.png`, name: `Devotee's Amulet`, rank: IRank.PURPLE },
  { icon: `iridescentSeal.png`, name: `Iridescent Seal`, rank: IRank.IRIDESCANT },
  { icon: `blackIncense.png`, name: `Black Incense`, rank: IRank.IRIDESCANT },
]

export const theWraith = [
  { icon: `theSerpent-Soot.png`, name: `"The Serpent" - Soot`, rank: IRank.BROWN },
  { icon: `theHound-Soot.png`, name: `"The Hound" - Soot`, rank: IRank.BROWN },
  { icon: `theGhost-Soot.png`, name: `"The Ghost" - Soot`, rank: IRank.BROWN },
  { icon: `theBeast-Soot.png`, name: `"The Beast" - Soot`, rank: IRank.BROWN },
  { icon: `boneClapper.png`, name: `Bone Clapper`, rank: IRank.YELLOW },
  { icon: `blink-Mud.png`, name: `"Blink" - Mud`, rank: IRank.YELLOW },
  { icon: `windstorm-Mud.png`, name: `"Windstorm" - Mud`, rank: IRank.YELLOW },
  { icon: `swiftHunt-Mud.png`, name: `"Swift Hunt" - Mud`, rank: IRank.YELLOW },
  { icon: `blindWarrior-Mud.png`, name: `"Blind Warrior" - Mud`, rank: IRank.YELLOW },
  { icon: `windstorm-White.png`, name: `"Windstorm" - White`, rank: IRank.GREEN },
  { icon: `swiftHunt-White.png`, name: `"Swift Hunt" - White`, rank: IRank.GREEN },
  { icon: `shadowDance-White.png`, name: `"Shadow Dance" - White`, rank: IRank.GREEN },
  { icon: `blink-White.png`, name: `"Blink" - White`, rank: IRank.GREEN },
  { icon: `blindWarrior-White.png`, name: `"Blind Warrior" - White`, rank: IRank.GREEN },
  { icon: `windstorm-Blood.png`, name: `"Windstorm" - Blood`, rank: IRank.PURPLE },
  { icon: `swiftHunt-Blood.png`, name: `"Swift Hunt" - Blood`, rank: IRank.PURPLE },
  { icon: `shadowDance-Blood.png`, name: `"Shadow Dance" - Blood`, rank: IRank.PURPLE },
  { icon: `allSeeing-Blood.png`, name: `"All Seeing" - Blood`, rank: IRank.PURPLE },
  { icon: `coxcombedClapper.png`, name: `Coxcombed Clapper`, rank: IRank.IRIDESCANT },
  { icon: `allSeeing-Spirit.png`, name: `"All Seeing" - Spirit`, rank: IRank.IRIDESCANT },
]

export const theSpirit = [
  { icon: `zori.png`, name: `Zōri`, rank: IRank.BROWN },
  { icon: `shiawaseAmulet.png`, name: `Shiawase Amulet`, rank: IRank.BROWN },
  { icon: `origamiCrane.png`, name: `Origami Crane`, rank: IRank.BROWN },
  { icon: `giftedBambooComb.png`, name: `Gifted Bamboo Comb`, rank: IRank.BROWN },
  { icon: `whiteHairRibbon.png`, name: `White Hair Ribbon`, rank: IRank.YELLOW },
  { icon: `rinsBrokenWatch.png`, name: `Rin's Broken Watch`, rank: IRank.YELLOW },
  { icon: `muddySportsDayCap.png`, name: `Muddy Sports Day Cap`, rank: IRank.YELLOW },
  { icon: `kaiunTalisman.png`, name: `Kaiun Talisman`, rank: IRank.YELLOW },
  { icon: `juniperBonsai.png`, name: `Juniper Bonsai`, rank: IRank.YELLOW },
  { icon: `rustyFlute.png`, name: `Rusty Flute`, rank: IRank.GREEN },
  { icon: `katsumoriTalisman.png`, name: `Katsumori Talisman`, rank: IRank.GREEN },
  { icon: `katanaTsuba.png`, name: `Katana Tsuba`, rank: IRank.GREEN },
  { icon: `dirtyUwabaki.png`, name: `Dirty Uwabaki`, rank: IRank.GREEN },
  { icon: `bloodyHairBrooch.png`, name: `Bloody Hair Brooch`, rank: IRank.GREEN },
  { icon: `yakuyokeAmulet.png`, name: `Yakuyoke Amulet`, rank: IRank.PURPLE },
  { icon: `wakizashiSaya.png`, name: `Wakizashi Saya`, rank: IRank.PURPLE },
  { icon: `prayerBeadsBracelet.png`, name: `Prayer Beads Bracelet`, rank: IRank.PURPLE },
  { icon: `driedCherryBlossom.png`, name: `Dried Cherry Blossom`, rank: IRank.PURPLE },
  { icon: `mother-DaughterRing.png`, name: `Mother-Daughter Ring`, rank: IRank.IRIDESCANT },
  { icon: `fathersGlasses.png`, name: `Father's Glasses`, rank: IRank.IRIDESCANT },
]

export const theOni = [
  { icon: `yakuyokeTalisman.png`, name: `Yakuyoke Talisman`, rank: IRank.BROWN },
  { icon: `rottingRope.png`, name: `Rotting Rope`, rank: IRank.BROWN },
  { icon: `crackedSakazuki.png`, name: `Cracked Sakazuki`, rank: IRank.BROWN },
  { icon: `blackenedToenail.png`, name: `Blackened Toenail`, rank: IRank.BROWN },
  { icon: `polishedMaedate.png`, name: `Polished Maedate`, rank: IRank.YELLOW },
  { icon: `inkLion.png`, name: `Ink Lion`, rank: IRank.YELLOW },
  { icon: `chippedSaihai.png`, name: `Chipped Saihai`, rank: IRank.YELLOW },
  { icon: `childsWoodenSword.png`, name: `Child's Wooden Sword`, rank: IRank.YELLOW },
  { icon: `bloodySash.png`, name: `Bloody Sash`, rank: IRank.YELLOW },
  { icon: `yamaokaSashimono.png`, name: `Yamaoka Sashimono`, rank: IRank.GREEN },
  { icon: `woodenOniMask.png`, name: `Wooden Oni Mask`, rank: IRank.GREEN },
  { icon: `shatteredWakizashi.png`, name: `Shattered Wakizashi`, rank: IRank.GREEN },
  { icon: `scalpedTopknot.png`, name: `Scalped Topknot`, rank: IRank.GREEN },
  { icon: `kanai-AnzenTalisman.png`, name: `Kanai-Anzen Talisman`, rank: IRank.GREEN },
  { icon: `tearSoakedTenugui.png`, name: `Tear Soaked Tenugui`, rank: IRank.PURPLE },
  { icon: `splinteredHull.png`, name: `Splintered Hull`, rank: IRank.PURPLE },
  { icon: `lionFang.png`, name: `Lion Fang`, rank: IRank.PURPLE },
  { icon: `akitosCrutch.png`, name: `Akito's Crutch`, rank: IRank.PURPLE },
  { icon: `renjirosBloodyGlove.png`, name: `Renjiro's Bloody Glove`, rank: IRank.IRIDESCANT },
  { icon: `iridescentFamilyCrest.png`, name: `Iridescent Family Crest`, rank: IRank.IRIDESCANT }
]
