import { IGameObject } from "../Common/game-object.model";
import { IRank } from "../Common/rank.model";

export const killerPerks: IGameObject[] = [
  { name: `A Nurse's Calling`, rank: IRank.PURPLE, icon: null },
  { name: `Agitation`, rank: IRank.PURPLE, icon: null },
  { name: `Barbecue & Chilli`, rank: IRank.PURPLE, icon: null },
  { name: `Bitter Murmur`, rank: IRank.PURPLE, icon: null },
  { name: `Blood Echo`, rank: IRank.PURPLE, icon: null },
  { name: `Blood Warden`, rank: IRank.PURPLE, icon: null },
  { name: `Bloodhound`, rank: IRank.PURPLE, icon: null },
  { name: `Brutal Strength`, rank: IRank.PURPLE, icon: null },
  { name: `Coulrophobia`, rank: IRank.PURPLE, icon: null },
  { name: `Cruel Limits`, rank: IRank.PURPLE, icon: null },
  { name: `Dark Devotion`, rank: IRank.PURPLE, icon: null },
  { name: `Dead Man's Switch`, rank: IRank.PURPLE, icon: null },
  { name: `Distressing`, rank: IRank.PURPLE, icon: null },
  { name: `Dying Light`, rank: IRank.PURPLE, icon: null },
  { name: `Franklin's Demise`, rank: IRank.PURPLE, icon: null },
  { name: `Furtive Chase`, rank: IRank.PURPLE, icon: null },
  { name: `Hex: Devour Hope`, rank: IRank.PURPLE, icon: null },
  { name: `Hex: Haunted Ground`, rank: IRank.PURPLE, icon: null },
  { name: `Hex: Huntress Lullaby`, rank: IRank.PURPLE, icon: null },
  { name: `Hex: No One Escapes Death`, rank: IRank.PURPLE, icon: null },
  { name: `Hex: Retribution`, rank: IRank.PURPLE, icon: null },
  { name: `Hex: Ruin`, rank: IRank.PURPLE, icon: null },
  { name: `Hex: The Third Seal`, rank: IRank.PURPLE, icon: null },
  { name: `Infectious Fright`, rank: IRank.PURPLE, icon: null },
  { name: `Insidious`, rank: IRank.PURPLE, icon: null },
  { name: `Iron Maiden`, rank: IRank.PURPLE, icon: null },
  { name: `Lightborn`, rank: IRank.PURPLE, icon: null },
  { name: `Mad Grit`, rank: IRank.PURPLE, icon: null },
  { name: `Make Your Choice`, rank: IRank.PURPLE, icon: null },
  { name: `Mindbreaker`, rank: IRank.PURPLE, icon: null },
  { name: `Monitor & Abuse`, rank: IRank.PURPLE, icon: null },
  { name: `Monstrous Shrine`, rank: IRank.PURPLE, icon: null },
  { name: `Nemesis`, rank: IRank.PURPLE, icon: null },
  { name: `Overcharge`, rank: IRank.PURPLE, icon: null },
  { name: `Play with Your Food`, rank: IRank.PURPLE, icon: null },
  { name: `Pop Goes the Weasel`, rank: IRank.PURPLE, icon: null },
  { name: `Rancor`, rank: IRank.PURPLE, icon: null },
  { name: `Remember Me`, rank: IRank.PURPLE, icon: null },
  { name: `Save the Best for Last`, rank: IRank.PURPLE, icon: null },
  { name: `Shadowborn`, rank: IRank.PURPLE, icon: null },
  { name: `Spies from the Shadows`, rank: IRank.PURPLE, icon: null },
  { name: `Surveillance`, rank: IRank.PURPLE, icon: null },
  { name: `Territorial Imperative`, rank: IRank.PURPLE, icon: null },
  { name: `Thanatophobia`, rank: IRank.PURPLE, icon: null },
  { name: `Thrilling Tremors`, rank: IRank.PURPLE, icon: null },
  { name: `Tinkerer`, rank: IRank.PURPLE, icon: null },
  { name: `Unrelenting`, rank: IRank.PURPLE, icon: null },
  { name: `Whispers`, rank: IRank.PURPLE, icon: null },
  { name: `Bamboozle`, rank: IRank.GREEN, icon: null },
  { name: `Beast of Prey`, rank: IRank.GREEN, icon: null },
  { name: `Corrupt Intervention`, rank: IRank.GREEN, icon: null },
  { name: `Deerstalker`, rank: IRank.GREEN, icon: null },
  { name: `Discordance`, rank: IRank.GREEN, icon: null },
  { name: `Enduring`, rank: IRank.GREEN, icon: null },
  { name: `Fire Up`, rank: IRank.GREEN, icon: null },
  { name: `Gearhead`, rank: IRank.GREEN, icon: null },
  { name: `Hangman's Trick`, rank: IRank.GREEN, icon: null },
  { name: `Hex: Thrill of the Hunt`, rank: IRank.GREEN, icon: null },
  { name: `I'm All Ears`, rank: IRank.GREEN, icon: null },
  { name: `Iron Grasp`, rank: IRank.GREEN, icon: null },
  { name: `Knock Out`, rank: IRank.GREEN, icon: null },
  { name: `Overwhelming Presence`, rank: IRank.GREEN, icon: null },
  { name: `Predator`, rank: IRank.GREEN, icon: null },
  { name: `Sloppy Butcher`, rank: IRank.GREEN, icon: null },
  { name: `Spirit Fury`, rank: IRank.GREEN, icon: null },
  { name: `Stridor`, rank: IRank.GREEN, icon: null },
  { name: `Surge`, rank: IRank.GREEN, icon: null },
  { name: `Unnerving Presence`, rank: IRank.GREEN, icon: null },
  { name: `Zanshin Tactics`, rank: IRank.GREEN, icon: null }
]