import { IGameObject } from "../Common/game-object.model";
import { IRank } from "../Common/rank.model";

export const SurvivorPerks: IGameObject[] = [
  { name: `Ace in the Hole`, rank: IRank.PURPLE, icon: null },
  { name: `Adrenaline`, rank: IRank.PURPLE, icon: null },
  { name: `Aftercare`, rank: IRank.PURPLE, icon: null },
  { name: `Alert`, rank: IRank.PURPLE, icon: null },
  { name: `Autodidact`, rank: IRank.PURPLE, icon: null },
  { name: `Boil Over`, rank: IRank.PURPLE, icon: null },
  { name: `Borrowed Time`, rank: IRank.PURPLE, icon: null },
  { name: `Botany Knowledge`, rank: IRank.PURPLE, icon: null },
  { name: `Breakout`, rank: IRank.PURPLE, icon: null },
  { name: `Buckle Up`, rank: IRank.PURPLE, icon: null },
  { name: `Calm Spirit`, rank: IRank.PURPLE, icon: null },
  { name: `Camaraderie`, rank: IRank.PURPLE, icon: null },
  { name: `Dance With Me`, rank: IRank.PURPLE, icon: null },
  { name: `Dark Sense`, rank: IRank.PURPLE, icon: null },
  { name: `Dead Hard`, rank: IRank.PURPLE, icon: null },
  { name: `Decisive Strike`, rank: IRank.PURPLE, icon: null },
  { name: `Déjà Vu`, rank: IRank.PURPLE, icon: null },
  { name: `Deliverance`, rank: IRank.PURPLE, icon: null },
  { name: `Detective's Hunch`, rank: IRank.PURPLE, icon: null },
  { name: `Distortion`, rank: IRank.PURPLE, icon: null },
  { name: `Fixated`, rank: IRank.PURPLE, icon: null },
  { name: `For the People`, rank: IRank.PURPLE, icon: null },
  { name: `Head On`, rank: IRank.PURPLE, icon: null },
  { name: `Hope`, rank: IRank.PURPLE, icon: null },
  { name: `Inner Strength`, rank: IRank.PURPLE, icon: null },
  { name: `Kindred`, rank: IRank.PURPLE, icon: null },
  { name: `Leader`, rank: IRank.PURPLE, icon: null },
  { name: `Lithe`, rank: IRank.PURPLE, icon: null },
  { name: `Lucky Break`, rank: IRank.PURPLE, icon: null },
  { name: `Mettle of Man`, rank: IRank.PURPLE, icon: null },
  { name: `No Mither`, rank: IRank.PURPLE, icon: null },
  { name: `No One Left Behind`, rank: IRank.PURPLE, icon: null },
  { name: `Object of Obsession`, rank: IRank.PURPLE, icon: null },
  { name: `Off the Record`, rank: IRank.PURPLE, icon: null },
  { name: `Open-Handed`, rank: IRank.PURPLE, icon: null },
  { name: `Pharmacy`, rank: IRank.PURPLE, icon: null },
  { name: `Poised`, rank: IRank.PURPLE, icon: null },
  { name: `Premonition`, rank: IRank.PURPLE, icon: null },
  { name: `Prove Thyself`, rank: IRank.PURPLE, icon: null },
  { name: `Resilience`, rank: IRank.PURPLE, icon: null },
  { name: `Saboteur`, rank: IRank.PURPLE, icon: null },
  { name: `Second Wind`, rank: IRank.PURPLE, icon: null },
  { name: `Self-Care`, rank: IRank.PURPLE, icon: null },
  { name: `Sole Survivor`, rank: IRank.PURPLE, icon: null },
  { name: `Spine Chill`, rank: IRank.PURPLE, icon: null },
  { name: `Sprint Burst`, rank: IRank.PURPLE, icon: null },
  { name: `Stake Out`, rank: IRank.PURPLE, icon: null },
  { name: `Streetwise`, rank: IRank.PURPLE, icon: null },
  { name: `This Is Not Happening`, rank: IRank.PURPLE, icon: null },
  { name: `Up the Ante`, rank: IRank.PURPLE, icon: null },
  { name: `Unbreakable`, rank: IRank.PURPLE, icon: null },
  { name: `Urban Evasion`, rank: IRank.PURPLE, icon: null },
  { name: `Vigil`, rank: IRank.PURPLE, icon: null },
  { name: `We'll Make It`, rank: IRank.PURPLE, icon: null },
  { name: `Any Means Necessary`, rank: IRank.GREEN, icon: null },
  { name: `Babysitter`, rank: IRank.GREEN, icon: null },
  { name: `Balanced Landing`, rank: IRank.GREEN, icon: null },
  { name: `Better Together`, rank: IRank.GREEN, icon: null },
  { name: `Bond`, rank: IRank.GREEN, icon: null },
  { name: `Breakdown`, rank: IRank.GREEN, icon: null },
  { name: `Diversion`, rank: IRank.GREEN, icon: null },
  { name: `Empathy`, rank: IRank.GREEN, icon: null },
  { name: `Flip-Flop`, rank: IRank.GREEN, icon: null },
  { name: `Iron Will`, rank: IRank.GREEN, icon: null },
  { name: `Left Behind`, rank: IRank.GREEN, icon: null },
  { name: `Lightweight`, rank: IRank.GREEN, icon: null },
  { name: `Plunderer's Instinct`, rank: IRank.GREEN, icon: null },
  { name: `Quick & Quiet`, rank: IRank.GREEN, icon: null },
  { name: `Red Herring`, rank: IRank.GREEN, icon: null },
  { name: `Slippery Meat`, rank: IRank.GREEN, icon: null },
  { name: `Small Game`, rank: IRank.GREEN, icon: null },
  { name: `Solidarity`, rank: IRank.GREEN, icon: null },
  { name: `Technician`, rank: IRank.GREEN, icon: null },
  { name: `Tenacity`, rank: IRank.GREEN, icon: null },
  { name: `Wake Up!`, rank: IRank.GREEN, icon: null },
  { name: `We're Gonna Live Forever`, rank: IRank.GREEN, icon: null },
  { name: `Windows of Opportunity`, rank: IRank.GREEN, icon: null },
]